identity_groups = [
    "Asian",
    "Black or African American",
    "Latino or Non-White Hispanic",
    "Middle Eastern",
    "Native American or Alaska Native",
    "Pacific Islander",
    "Non-Hispanic White",
    "Atheists",
    "Buddhists",
    "Christians",
    "Hindus",
    "Jews",
    "Mormons",
    "Muslims",
    "Immigrants",
    "Migrant Workers",
    "People Originated From a Specific Country",
    "Undocumented People",
    "Refugees",
    "Men",
    "Non-Binary or Third Gender Identity",
    "Transgender Men",
    "Transgender (Unspecified)",
    "Transgender Women",
    "Women",
    "Bisexual",
    "Gay",
    "Lesbian",
    "Heterosexual",
    "People With Physical Disabilities",
    "People With Cognitive Disorders or Learning Disability Status",
    "People With Mental Health Problems",
    "Visually Impaired People",
    "Hearing Impaired People",
]


